name: 'install_conan_packages'
description: 'installs required packages using conan'
inputs:
  os: 
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Install conan packages (Windows)
      shell: cmd
      if: ${{ inputs.os == 'windows-2022' }}
      run: conan install . --output-folder=build-rel -g CMakeToolchain -pr:b conanprofile.windows.txt -pr:h conanprofile.windows.txt --build=missing

    - name: Install conan packages (Linux + GLFW3)
      shell: bash 
      if: ${{ inputs.os == 'ubuntu-22.04' }}
      run: conan install . --output-folder=build-rel -g CMakeToolchain -pr:b conanprofile.linux.txt -pr:h conanprofile.linux.txt --build=missing
